version: "2.1"

services:
  camera:
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.kernel-modules: "1"
    container_name: birdbox-camera
    privileged: true
    build:
      context: ./camera
    volumes:
      - pics:/pics
      - schedule:/schedule
      - auth:/auth
    ports:
      - 80:80
    restart: unless-stopped
  # syncthing:
  #   image: linuxserver/syncthing:arm32v7-latest
  #   container_name: syncthing
  #   environment:
  #     - UMASK_SET=<022>
  #   volumes:
  #     - syncthingconfig:/config
  #     - pics:/pics
  #     - schedule:/schedule
  #     - auth:/auth
  #   ports:
  #     - 8384:8384
  #     - 22000:22000
  #     - 21027:21027/udp
  #   restart: unless-stopped
volumes:
  # syncthingconfig:
  pics:
  schedule:
  auth:
