version: "2.1"

services:
  camera:
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.kernel-modules: "1"
    container_name: birdbox-camera
    privileged: true
    build:
      context: ./camera
    volumes:
      - pics:/pics
      - schedule:/schedule
      - auth:/auth
    ports:
      - 80:80
    restart: unless-stopped
volumes:
  pics:
  schedule:
  auth:
