version: "2.1"

services:
  camera:
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.kernel-modules: "1"
    container_name: birdbox-camera
    privileged: true
    build:
      context: ./camera
    volumes:
      - pictures:/data
    ports:
      - 80:80
    restart: unless-stopped
volumes:
  pictures:
