FROM balenalib/%%BALENA_MACHINE_NAME%%-python

RUN apt-get update && \
    apt-get upgrade && \
    apt install ffmpeg

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN READTHEDOCS=True pip install -r /requirements.txt

EXPOSE 80

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["bash","start.sh"]
